export const Images = {
  logo: require("./Logo-no-bg_1.png"),
  search_logo: require("./magnifying-glass.png"),
  cancle_logo: require("./cancle_logo.png"),
  flash_logo: require("./flash.png"),
  change_camera_logo: require("./Change_Camera.png"),
  emoji_selector_logo: require("./emoji_selector.png"),
  notification_logo: require("./Notification.png"),
  filter_logo: require("./filter_logo.png"),
  story_1: require("./story_1.png"),
  story_2: require("./story_2.png"),
  story_3: require("./story_3.png"),
  story_4: require("./story_4.png"),
  my_story: require("./my_story.png"),
  plus_icon: require("./plus_icon.png"),
  post_user: require("./post_user.png"),
  post_image: require("./post_image.png"),
  like_icon: require("./like_icon.png"),
  comment_icon: require("./comment_icon.png"),
  share_icon: require("./share_icon.png"),
  badge_icon: require("./badge_icon.png"),
  options_icon: require("./options_icon.png"),
  verified_icon: require("./verified_icon.png"),
  home_icon: require("./home_icon.png"),
  chat_icon: require("./chat_icon.png"),
  big_plus_icon: require("./big_plus_icon.png"),
  wallet_icon: require("./wallet_icon.png"),
};
